### ISSUE TITLE
Where is base.html?

### ISSUE THREAD

**Issue by linjan** [alan-hicks/django-dmarc#1]
Hello,

Where is base.html, that is required? It indicated in report.html.
https://github.com/alan-hicks/django-dmarc/search?utf8=%E2%9C%93&q=base.html

**Comment by alan-hicks** [comment]
Django-dmarc is intended to be used as an app in your project and so base.html will come from your project. See https://docs.djangoproject.com/en/1.7/topics/templates/

**Comment by linjan** [comment]
Thanks,

can you provide base.html, that is used in your project?

**Comment by alan-hicks** [comment]
The one in the docs is great to start with, you can add and update it to your requirements.

**Comment by linjan** [comment]
Okay, but in your project you use some CSS, i think.
Please, help me with that, i just want to do like in your screenshot: https://github.com/alan-hicks/django-dmarc/blob/master/docs/images/dmarc-report.png

**Comment by linjan** [comment]
I'll show you, what I have now: https://dl.dropboxusercontent.com/1/view/gqhj09rk6i8rkfq/Apps/Shutter/1870db28.png

**Comment by linjan** [comment]
Thanks for fast answer,

I commented issue again. Please, help me with that.

**Comment by alan-hicks** [comment]
I'm using Bootstrap http://getbootstrap.com/ for styling, I've also added the optional dependency in the docs and credited you in the changelog. Also added is a sample report.html.
Thanks for your contribution Jan.
