### ISSUE TITLE
Miscellaneous improvements

### ISSUE THREAD

**Issue by virtualtam** [alan-hicks/django-dmarc#2]
Hi @alan-hicks and thanks for publishing `django-dmarc` as an open-source project :)

I was looking for a web-based tool to automate DMARC report processing, and thought that `django-dmarc` would be a nice base for a self-hosted alternative to [dmarcian](https://dmarcian.com/dmarc-inspector/) (and similar tools).

To this effect, I've forked the repository and started a sandbox branch at https://github.com/virtualtam/django-dmarc/tree/vt/master , that currently features the following additions and changes:

- add the [Tox](https://tox.readthedocs.io/en/latest/) virtualenv management tool to automate managing test environments
- add Python linters: [isort](https://github.com/timothycrosley/isort/), [Pycodestyle](http://pycodestyle.pycqa.org/en/latest/intro.html) (formerly pep8), [Pylint](https://www.pylint.org/)
- add Python 3.x-compatibility
- add a demo Django project for quick testing/demoing
- update packaging / setuptools settings
- fix (most) lint errors

Notes:
- the commits have been kept atomic to ease reviewing
- the documentation would need to be updated to reflect the latest changes
- I plan on adding / improving the following features / integrations before using this project in a production environment:
    - Travis CI integration
    - Docker image
    - broader test coverage
    - more idiomatic Django-ORM queries

Would you be interested in integrating these changes into your repository? I'd be happy to rework my modifications so the commits can be upstreamed :)

Regards,

VirtualTam

**Comment by webtweakers** [comment]
Good fork! I would be interested in this as well, plus Django 2+ support, which is failing at the moment. The foreign-keys in the models now require the 'on_delete' argument, which is missing.

**Comment by alan-hicks** [comment]
Just pushed minor changes for Django 2.0, thanks @webtweakers for the prompt. Alas no time for more.

**Comment by webtweakers** [comment]
Thanks for the quick response. Unfortunately the 2nd migration file is incompatible with Django 2.0, which makes it impossible to use the django-dmarc in a Django 2.0 project.

This is actually explicitly mentioned in the [docs](https://docs.djangoproject.com/en/2.1/releases/1.9/#foreignkey-and-onetoonefield-on-delete-argument):

> In order to increase awareness about cascading model deletion, the on_delete argument of ForeignKey and OneToOneField will be required in Django 2.0.
> 
> **Update models and existing migrations to explicitly set the argument.** Since the default is models.CASCADE, add on_delete=models.CASCADE to all ForeignKey and OneToOneFields that don’t use a different option. You can also pass it as the second positional argument if you don’t care about compatibility with older versions of Django.

Note the "existing migrations" part: that's where django-dmarc 0.5.2 still breaks.

I've created [a fork](https://github.com/webtweakers/django-dmarc/tree/vt/master), branched of @virtualtam's work, where I have reset the migrations.

**Comment by alan-hicks** [comment]
Finally updated this project and included as many of your contributions as I could.
Sincere thanks @webtweakers and @virtualtam and apologies for unusually long delay.
